-- Migration: Add declarations table for agent customs declaration entries

CREATE TABLE IF NOT EXISTS `declarations` (
  `declaration_id` INT(11) NOT NULL AUTO_INCREMENT,
  `shipment_id` INT(11) NOT NULL,
  -- Parties and references
  `consignor_name` VARCHAR(150) NULL,
  `consignee_name` VARCHAR(150) NULL,
  `consignee_address` TEXT NULL,
  `declarant_name` VARCHAR(150) NULL,
  `declaration_type` VARCHAR(50) NULL,
  `clearance_office` VARCHAR(100) NULL,
  `registration_no` VARCHAR(50) NULL,
  `registration_date` DATE NULL,
  `financial` VARCHAR(50) NULL,
  -- Countries and routing
  `country_consignor` VARCHAR(3) NULL,
  `country_dispatch` VARCHAR(3) NULL,
  `country_origin` VARCHAR(3) NULL,
  `country_destination` VARCHAR(3) NULL,
  `delivery_terms` VARCHAR(10) NULL,
  `delivery_place` VARCHAR(100) NULL,
  -- Currency and totals
  `currency` VARCHAR(3) NOT NULL,
  `currency_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `exchange_rate` DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
  `statistical_value_mwk` DECIMAL(15,2) NULL,
  -- Transport and logistics
  `means_of_transport_arrival` VARCHAR(50) NULL,
  `means_of_transport_border` VARCHAR(50) NULL,
  `departure_date` DATE NULL,
  `place_loading` VARCHAR(100) NULL,
  `location_goods` VARCHAR(100) NULL,
  `office_entry_exit` VARCHAR(100) NULL,
  `packages_description` TEXT NULL,
  `package_type` VARCHAR(20) NULL,
  `num_packages` INT(11) NULL,
  `gross_weight` DECIMAL(12,3) NULL,
  `net_weight` DECIMAL(12,3) NULL,
  `commodity_code` VARCHAR(20) NULL,
  `goods_description` TEXT NULL,
  `invoice_value` DECIMAL(15,2) NULL,
  `units` INT(11) NULL,
  -- Tax base and duties (MWK)
  `tax_base_mwk` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `ait_rate` DECIMAL(10,4) NULL,
  `ait_amount_mwk` DECIMAL(15,2) NULL,
  `icd_rate` DECIMAL(10,4) NULL,
  `icd_amount_mwk` DECIMAL(15,2) NULL,
  `exc_rate` DECIMAL(10,4) NULL,
  `exc_amount_mwk` DECIMAL(15,2) NULL,
  `vat_rate` DECIMAL(10,4) NULL,
  `vat_amount_mwk` DECIMAL(15,2) NULL,
  `lev_rate` DECIMAL(10,4) NULL,
  `lev_amount_mwk` DECIMAL(15,2) NULL,
  `total_fees_mwk` DECIMAL(15,2) NULL,
  `total_declaration_mwk` DECIMAL(15,2) NULL,
  -- Accounting details
  `mode_of_payment` VARCHAR(50) NULL,
  `assessment_number` VARCHAR(50) NULL,
  `receipt_number` VARCHAR(50) NULL,
  `bank_code` VARCHAR(20) NULL,
  -- Attachments
  `scanned_form_path` VARCHAR(500) NULL,
  `notes` TEXT NULL,
  `created_by` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`declaration_id`),
  KEY `shipment_id` (`shipment_id`),
  CONSTRAINT `declarations_ibfk_1` FOREIGN KEY (`shipment_id`) REFERENCES `shipments`(`shipment_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
